// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDTHjqVjO765vrcd5xdK-ReYBgiLwQk6o',
    appId: '1:83217195351:web:529802f078bbd5bcb31e12',
    messagingSenderId: '83217195351',
    projectId: 'locacao-salas',
    authDomain: 'locacao-salas.firebaseapp.com',
    storageBucket: 'locacao-salas.appspot.com',
    measurementId: 'G-Z2DZVX0Z63',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMwuY0WnyS3YbAM0bfMsi_0xblIEIBLfM',
    appId: '1:83217195351:android:300c6118406e67d4b31e12',
    messagingSenderId: '83217195351',
    projectId: 'locacao-salas',
    storageBucket: 'locacao-salas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1qCP2huZ9wz7mmv4fvyZ6uBc0j6OMoxs',
    appId: '1:83217195351:ios:30ad40b4d39779feb31e12',
    messagingSenderId: '83217195351',
    projectId: 'locacao-salas',
    storageBucket: 'locacao-salas.appspot.com',
    iosClientId: '83217195351-hbou28cl3ifeckiame7s6aljd7kifqfd.apps.googleusercontent.com',
    iosBundleId: 'com.example.formularioAmanda',
  );
}
